#!/usr/bin/env node

const MockPlugin = require('../lib/MockPlugin')

const plugin = new MockPlugin(process.argv[2])
plugin.listen()
  .then(_ => {
    console.log('Listening at http://localhost:3333')
    plugin.server.ref() // don't exit right away
  })
