#!/bin/sh

set -e

# --project-name because of https://github.com/docker/compose/issues/5874
exec docker-compose --project-name overviewserver up --build --abort-on-container-exit --exit-code-from dev
