#!/bin/bash

# helper script for foreman to start processes.
# Uses the print-classpath task to generate the correct classpath.
#
# Usage: startHelper projectDir commandParameters

project=$1
shift

CLASSPATH=`play $project/print-classpath | grep -v -e '\[.*info.*]' -e '\[.*success.*]' -e 'Waiting for lock'`

java $JAVA_OPTS -cp "$CLASSPATH" $@
