#!/bin/bash

# 'kops edit cluster' calls EDITOR. This is our EDITOR.

FILE="$1"

if grep -q 'additionalPolicies:' "$FILE"; then
  echo 'kube2iam additionalPolicies already exist'
else
  echo 'Adding sts:AssumeRole additionalPolicy'
  cat >> "$FILE" <<EOT
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": ["*"]
        }
      ]
EOT
fi
