#!/bin/bash

source "$(dirname "$0")"/env
AWS="aws"

debug_command_output() {
  echo -e "\e[32m  ==> $1\e[0m" >&2
}

debug_command() {
  echo -e "\e[36m$*\e[0m" >&2
}

fail() {
  echo -e "\e[1m\e[31m$1\e[0m" >&2
  exit 1
}

callaws() {
  debug_command "$AWS $@"
  set +e
  OUTPUT="$($AWS "$@" 2>&1)"
  RET=$?
  set -e

  if [ "$RET" = "0" ]; then
    debug_command_output "$OUTPUT"
    echo "$OUTPUT" # to stdout
  else
    if echo "$OUTPUT" | grep --silent EntityAlreadyExists; then
      debug_command_output "(EntityAlreadyExists; continuing)" # and we're fine
    elif echo "$OUTPUT" | grep --silent LimitExceeded; then
      debug_command_output "(LimitExceeded; continuing)" # and we're fine
    elif echo "$OUTPUT" | grep --silent InvalidPermission.Duplicate; then
      debug_command_output "(InvalidPermission.Duplicate; continuing)" # and we're fine
    elif echo "$OUTPUT" | grep --silent InvalidGroup.Duplicate; then
      debug_command_output "(Invalidroup.Duplicate; continuing)" # and we're fine
    elif echo "$OUTPUT" | grep --silent RepositoryAlreadyExistsException; then
      debug_command_output "(RepositoryAlreadyExistsException; continuing)" # and we're fine
    elif echo "$OUTPUT" | grep --silent "has been taken in this account, please try a different suffix"; then
      debug_command_output "(has been taken in this account, please try a different suffix; continuing)" # and we're fine
    else
      fail "$OUTPUT"
    fi
  fi
}
