#!/bin/bash

source "$(dirname "$0")"/common

: ${CLUSTER_NAME?You must set CLUSTER_NAME}
: ${VPC_ID?You must set VPC_ID}

callaws ec2 create-security-group \
  --vpc-id $VPC_ID \
  --description ingress.$CLUSTER_NAME \
  --group-name ingress.$CLUSTER_NAME

sgidingress=$(callaws ec2 describe-security-groups --filters Name=group-name,Values=ingress.$CLUSTER_NAME --output text --query 'SecurityGroups[*].GroupId')
sgidnode=$(callaws ec2 describe-security-groups --filters Name=group-name,Values=nodes.$CLUSTER_NAME --output text --query 'SecurityGroups[*].GroupId')

callaws ec2 authorize-security-group-ingress \
  --group-id $sgidingress \
  --protocol tcp --port 443 --cidr 0.0.0.0/0

callaws ec2 authorize-security-group-ingress \
  --group-id $sgidingress \
  --protocol tcp --port 80 --cidr 0.0.0.0/0

callaws ec2 authorize-security-group-ingress \
  --group-id $sgidnode \
  --protocol all --port -1 --source-group $sgidingress

callaws ec2 create-tags \
  --resources $sgidingress \
  --tags "[{\"Key\": \"kubernetes.io/cluster/$CLUSTER_NAME\", \"Value\": \"owned\"}, {\"Key\": \"kubernetes:application\", \"Value\": \"kube-ingress-aws-controller\"}]"
