#!/bin/bash

source "$(dirname "$0")"/common

DIR="$(dirname "$0")"

set -e

: ${ENVIRONMENT?You must set ENVIRONMENT environment variable}

echo "Creating buckets..."

callaws s3 mb s3://overview-$ENVIRONMENT-file-contents
callaws s3 mb s3://overview-$ENVIRONMENT-file-view

echo "Creating roles..."

AWS_ACCOUNT_ID=$(callaws sts get-caller-identity --output text --query Account)
ASSUME_ROLE_POLICY="$(cat "$DIR"/policies/assume-role.json | sed -e "s/\$ENVIRONMENT/$ENVIRONMENT/g" | sed -e "s/\$AWS_ACCOUNT_ID/$AWS_ACCOUNT_ID/g")"

POLICY="$(cat "$DIR"/policies/overview-web.json | sed -e "s/\$ENVIRONMENT/$ENVIRONMENT/g")"
callaws iam create-role \
  --role-name=overview-$ENVIRONMENT-web \
  --assume-role-policy-document="$ASSUME_ROLE_POLICY"
callaws iam update-assume-role-policy \
  --role-name=overview-$ENVIRONMENT-web \
  --policy-document="$ASSUME_ROLE_POLICY"
callaws iam put-role-policy \
  --role-name overview-$ENVIRONMENT-web \
  --policy-name overview-$ENVIRONMENT-web-policy \
  --policy-document "$POLICY"

POLICY="$(cat "$DIR"/policies/overview-worker.json | sed -e "s/\$ENVIRONMENT/$ENVIRONMENT/g")"
callaws iam create-role \
  --role-name=overview-$ENVIRONMENT-worker \
  --assume-role-policy-document="$ASSUME_ROLE_POLICY"
callaws iam update-assume-role-policy \
  --role-name=overview-$ENVIRONMENT-worker \
  --policy-document="$ASSUME_ROLE_POLICY"
callaws iam put-role-policy \
  --role-name overview-$ENVIRONMENT-worker \
  --policy-name overview-$ENVIRONMENT-worker-policy \
  --policy-document "$POLICY"

POLICY="$(cat "$DIR"/policies/kube-ingress-alb.json)"
callaws iam create-role \
  --role-name=$ENVIRONMENT-kube-ingress-alb \
  --assume-role-policy-document="$ASSUME_ROLE_POLICY"
callaws iam update-assume-role-policy \
  --role-name=$ENVIRONMENT-kube-ingress-alb \
  --policy-document="$ASSUME_ROLE_POLICY"
callaws iam put-role-policy \
  --role-name $ENVIRONMENT-kube-ingress-alb \
  --policy-name $ENVIRONMENT-kube-ingress-alb \
  --policy-document "$POLICY"

POLICY="$(cat "$DIR"/policies/external-dns.json)"
callaws iam create-role \
  --role-name=$ENVIRONMENT-external-dns \
  --assume-role-policy-document="$ASSUME_ROLE_POLICY"
callaws iam update-assume-role-policy \
  --role-name=$ENVIRONMENT-external-dns \
  --policy-document="$ASSUME_ROLE_POLICY"
callaws iam put-role-policy \
  --role-name $ENVIRONMENT-external-dns \
  --policy-name $ENVIRONMENT-external-dns-policy \
  --policy-document "$POLICY"

# And a default role, with no permissions, for all the pods that should run
# without any AWS API access at all:
callaws iam create-role \
  --role-name=$ENVIRONMENT-overview-default-role \
  --assume-role-policy-document="$ASSUME_ROLE_POLICY"
callaws iam update-assume-role-policy \
  --role-name=$ENVIRONMENT-overview-default-role \
  --policy-document="$ASSUME_ROLE_POLICY"
