#!/bin/bash

source "$(dirname "$0")"/common

DIR="$(dirname "$0")"

set -e

echo "Creating buckets..."

callaws s3 mb s3://overview-$ENVIRONMENT-file-contents
callaws s3 mb s3://overview-$ENVIRONMENT-file-view

echo "Creating roles..."

AWS_ACCOUNT_ID=$(callaws sts get-caller-identity --output text --query Account)
ASSUME_ROLE_POLICY="$(cat "$DIR"/policies/assume-role.json | sed -e "s/\$ENVIRONMENT/$ENVIRONMENT/g" | sed -e "s/\$AWS_ACCOUNT_ID/$AWS_ACCOUNT_ID/g")"

POLICY="$(cat "$DIR"/policies/overview-web.json | sed -e "s/\$ENVIRONMENT/$ENVIRONMENT/g")"
callaws iam create-role \
  --role-name=overview-$ENVIRONMENT-web \
  --assume-role-policy-document="$ASSUME_ROLE_POLICY"

callaws iam put-role-policy \
  --role-name overview-$ENVIRONMENT-web \
  --policy-name overview-$ENVIRONMENT-web-policy \
  --policy-document "$POLICY"

callaws iam create-role \
  --role-name=overview-$ENVIRONMENT-worker \
  --assume-role-policy-document="$ASSUME_ROLE_POLICY"

POLICY="$(cat "$DIR"/policies/overview-worker.json | sed -e "s/\$ENVIRONMENT/$ENVIRONMENT/g")"
callaws iam put-role-policy \
  --role-name overview-$ENVIRONMENT-worker \
  --policy-name overview-$ENVIRONMENT-worker-policy \
  --policy-document "$POLICY"

# Our "kube-ingress-alb" role spans all clusters.
callaws iam create-role \
  --role-name=kube-ingress-alb \
  --assume-role-policy-document="$ASSUME_ROLE_POLICY"

POLICY="$(cat "$DIR"/policies/kube-ingress-alb.json)"
callaws iam put-role-policy \
  --role-name kube-ingress-alb \
  --policy-name kube-ingress-alb-policy \
  --policy-document "$POLICY"

# Our "extenral-dns" role spans all clusters.
callaws iam create-role \
  --role-name=external-dns \
  --assume-role-policy-document="$ASSUME_ROLE_POLICY"

POLICY="$(cat "$DIR"/policies/external-dns.json)"
callaws iam put-role-policy \
  --role-name external-dns \
  --policy-name external-dns-policy \
  --policy-document "$POLICY"

# And a default role, with no permissions, for all the pods that should run
# without any AWS API access at all:
callaws iam create-role \
  --role-name=overview-default-role \
  --assume-role-policy-document="$ASSUME_ROLE_POLICY"
