#!/bin/bash

CLUSTER_NAME=staging.overviewdocs.com
STATE_BUCKET="s3://kops-state.$CLUSTER_NAME"

echo "*****"
echo "*****"
echo "Please log in to AWS and delete the staging load balancer and target group!"
echo "*****"
echo "(Some bug means kops doesn't delete them for us.)"
echo "*****"
echo "*****"

kops delete cluster \
  --state="$STATE_BUCKET" \
  --name=$CLUSTER_NAME \
  "$@" # force user to add "--yes"
