#!/bin/bash

DIR="$(dirname "$0")"
AWS_DIR="$DIR"/../../aws

source "$AWS_DIR"/common

set -e

AWS_ACCOUNT_ID=$(callaws sts get-caller-identity --output text --query Account)
ENVIRONMENT=production

ASSUME_ROLE_POLICY="$(cat "$AWS_DIR"/policies/assume-role.json | sed -e "s/\$ENVIRONMENT/$ENVIRONMENT/g" | sed -e "s/\$AWS_ACCOUNT_ID/$AWS_ACCOUNT_ID/g")"
POLICY="$(cat "$DIR"/policies/k8s-snapshots.json | sed -e "s/\$AWS_ACCOUNT_ID/$AWS_ACCOUNT_ID/g")"
callaws iam create-role \
  --role-name=$ENVIRONMENT-k8s-snapshots \
  --assume-role-policy-document="$ASSUME_ROLE_POLICY"
callaws iam update-assume-role-policy \
  --role-name=$ENVIRONMENT-k8s-snapshots \
  --policy-document="$ASSUME_ROLE_POLICY"
callaws iam put-role-policy \
  --role-name $ENVIRONMENT-k8s-snapshots \
  --policy-name $ENVIRONMENT-k8s-snapshots-policy \
  --policy-document "$POLICY"
