#!/bin/sh
#
# Tests that all our images work together as expected. Writes to
# ../integration-test/test-results.xml.

set -e
set -x

DIR="$(dirname "$0")"
OVERVIEW_VERSION=$(git rev-parse HEAD)
PROJECT="overviewintegrationtest"

DOCKER_COMPOSE="docker-compose --project-name $PROJECT -f $DIR/integration-test.yml"

OVERVIEW_VERSION=$OVERVIEW_VERSION $DOCKER_COMPOSE down -v # in case a previous run errored out

# overview-database must be running before we start overview-web and
# overview-worker. That's a bug in overview-web and another bug in
# overview-worker. Rather than fix the bug, we'll just start it here;
# we're guaranteed it'll be up after overview-db-evolution-applier is
# run, so it will be up when we start everything else.
OVERVIEW_VERSION=$OVERVIEW_VERSION $DOCKER_COMPOSE up -d overview-database

OVERVIEW_VERSION=$OVERVIEW_VERSION $DOCKER_COMPOSE run overview-db-evolution-applier

OVERVIEW_VERSION=$OVERVIEW_VERSION $DOCKER_COMPOSE up \
  --abort-on-container-exit \
  --exit-code-from overview-integration-test \
  overview-integration-test

OVERVIEW_VERSION=$OVERVIEW_VERSION $DOCKER_COMPOSE down -v
