#!/bin/sh
#
# Runs all our unit tests: those in Node and in Scala. Writes to
# ../unit-test-results (wiping the directory and creating it)

set -e
set -x

DIR="$(dirname "$0")"
ABSOLUTE_DIR="$(realpath "$DIR"/..)"

cleanup() {
  for container in $(docker ps -f name=overview-unit-test- -q); do
    docker rm -f $container
  done
  for network in $(docker network ls -f name=overview-unit-test -q); do
    docker network rm $network
  done
}

fail() {
  cleanup
  exit 1
}

cleanup # from a previous, failed run

docker network create overview-unit-test
docker volume create overviewserver_homedir # if it doesn't already exist

DOCKER_RUN="docker run --rm --network overview-unit-test"

# Use network aliases because unit-test addresses are hard-coded
$DOCKER_RUN -d --name overview-unit-test-database --network-alias database overview-database:latest || fail
$DOCKER_RUN -d --name overview-unit-test-redis --network-alias redis overview-redis:latest || fail

$DOCKER_RUN --name overview-unit-test-dev \
  --volume overviewserver_homedir:/root \
  --volume "$ABSOLUTE_DIR":/app overview-dev:latest \
  sh -c 'set -x; rm -rf unit-test-results && mkdir unit-test-results && auto/test-coffee-once.sh && ./sbt all/test && find /root/overview-build -name "com.overviewdocs.*.xml" -exec cp {} /app/unit-test-results/ \;' \
  || fail

cleanup
