#!/bin/sh

set -e

DIR="$(dirname "$0")"
. "$DIR"/common

echo "Specifying volumes..."
apply_template $ENVIRONMENT-volumes.yml

evolve_database
echo "Database evolved. Starting Overview..."

apply_template redis.yml
apply_template worker.yml
apply_template web.yml
apply_template convert-archive.yml
apply_template convert-image.yml
apply_template convert-office.yml

echo "Building ingress..."
apply_template $ENVIRONMENT-ingress.yml
