---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: convert-text-deployment
spec:
  selector:
    matchLabels:
      app: convert-text
  replicas: 1
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: convert-text
    spec:
      containers:
      - name: convert-text
        image: CONVERT_TEXT_IMAGE
        env:
        - name: POLL_URL
          value: http://overview-worker:9032/Text
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 1
            memory: 500Mi # total guess
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: convert-text
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: convert-text-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
