---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: convert-pdf-deployment
spec:
  selector:
    matchLabels:
      app: convert-pdf
  replicas: 1
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: convert-pdf
    spec:
      containers:
      - name: convert-pdf
        image: CONVERT_PDF_IMAGE
        env:
        - name: POLL_URL
          value: http://overview-worker:9032/Pdf
        resources:
          requests:
            cpu: 500m
            memory: 500Mi # total guess
          limits:
            cpu: 1
            memory: 500Mi # total guess
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: convert-pdf
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: convert-pdf-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
