---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: convert-archive-deployment
spec:
  selector:
    matchLabels:
      app: convert-archive
  replicas: 1
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: convert-archive
    spec:
      containers:
      - name: convert-archive
        image: CONVERT_ARCHIVE_IMAGE
        env:
        - name: POLL_URL
          value: http://overview-worker:9032/Archive
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 1
            memory: 100Mi # convert-archive should always use next to nothing
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: convert-archive
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: convert-archive-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
