#!/bin/bash
#
# This is run by Jenkins. It should update the Overview cluster to the latest version

set -e
#set -x

if [ ! -d ~/bin ]; then
  mkdir -p ~/bin
fi
export PATH="$HOME/bin:$PATH"

if [ ! -x ~/bin/kubectl ]; then
  curl -L https://storage.googleapis.com/kubernetes-release/release/v1.17.5/bin/linux/amd64/kubectl > ~/bin/kubectl
  chmod +x ~/bin/kubectl
fi

cd "$(dirname "$0")"
DIR="$(dirname "$0")"
ENVIRONMENT=production

# We're in Jenkins, so HEAD is the version we want to push.
# Jenkins guarantees that at the time we call this, images have been pushed to
# Docker Hub.
VERSION=$(git rev-parse HEAD)
. "$DIR"/common

echo "Updating db-evolution-applier, web and worker to version ${SHA1}"

evolve_database

apply_template web.yml
apply_template worker.yml
apply_template convert-archive.yml
apply_template convert-email.yml
apply_template convert-html.yml
apply_template convert-image.yml
apply_template convert-office.yml
apply_template convert-pdf.yml
apply_template convert-pdfocr.yml
apply_template convert-pst.yml
apply_template convert-text.yml
