apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: worker
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: worker
      containers:
      - name: worker
        image: overview/overview-worker:VERSION
        volumeMounts:
        - name: searchindex
          mountPath: /var/lib/overview/searchindex
        ports:
        - containerPort: 9030 # communicate with web
        - containerPort: 9032 # listen for converters
        envFrom:
        - configMapRef:
            name: database-config
        env:
        - name: MESSAGE_BROKER_HOSTNAME
          value: overview-worker
          # TODO Rearchitect message broker. Should it be a stateful service?
          # Whatever the case, this will break if we have two message brokers
          # running concurrently.
        - name: MESSAGE_BROKER_BIND_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: BLOB_STORAGE_FILE_CONTENTS_LOCATION
          value: s3:BLOB_STORAGE_FILE_CONTENTS_S3_BUCKET
        - name: BLOB_STORAGE_FILE_VIEW_LOCATION
          value: s3:BLOB_STORAGE_FILE_VIEW_S3_BUCKET
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: overview-db-user
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: overview-db-user
              key: password
        resources:
          requests:
            cpu: 1500m
            memory: 5Gi
          limits:
            cpu: 1500m
            memory: 5Gi
      volumes:
      - name: searchindex
        persistentVolumeClaim:
          claimName: searchindex-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: overview-worker
  labels:
    app: worker
spec:
  ports:
  - port: 9030
    protocol: TCP
    name: akka-message-broker
  - port: 9032
    protocol: TCP
    name: http-convert-server
  selector:
    app: worker
